// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aHSIjy_T_MdLNQXNRwyw0iQr8R55-8A',
    appId: '1:445204057855:web:c8e53e71684725238386ca',
    messagingSenderId: '445204057855',
    projectId: 'settle-this-dev',
    authDomain: 'settle-this-dev.firebaseapp.com',
    storageBucket: 'settle-this-dev.firebasestorage.app',
    measurementId: 'G-QP7JRHWVSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKqSy-0ro_zWItQozfUo-33krtr8geHD4',
    appId: '1:445204057855:android:7cc99e39801843d78386ca',
    messagingSenderId: '445204057855',
    projectId: 'settle-this-dev',
    storageBucket: 'settle-this-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALV0GaudiwvWJNYkFl3hqKdX6K7JK5olE',
    appId: '1:445204057855:ios:24d9cc60997e4e088386ca',
    messagingSenderId: '445204057855',
    projectId: 'settle-this-dev',
    storageBucket: 'settle-this-dev.firebasestorage.app',
    iosBundleId: 'com.athletedomains.settleThis',
  );
}
