import 'package:flutter/material.dart';

import '../../app/theme.dart';

/// The expressive pose Pip strikes for a given surface. Each maps to a
/// reference-consistent art asset generated from the locked canon hero
/// (see `assets/pip/PIP_CANON.md` and `tools/pip-gen/`).
enum PipPose {
  /// Gavel mid-swing, confident wink. Default hero / "verdict delivered".
  triumph('pip_triumph'),

  /// Gavel struck down on the block — the "gavel drops" reveal beat.
  gavelDown('pip_gavel_down'),

  /// Gavel set down, wings folded, empathetic. Soft-redirect / sensitive.
  listening('pip_listening'),

  /// Looking up, wing to chin, sparkles. Loading / "thinking it over".
  thinking('pip_thinking'),

  /// Wings out, palms up. Ambiguous verdicts / not-enough-evidence.
  shrug('pip_shrug'),

  /// Flustered, papers fluttering. Error states.
  oops('pip_oops');

  const PipPose(this.asset);

  /// Base filename (without extension) under `assets/pip/`.
  final String asset;

  /// Poses where the energy drops — used to pick the stub fallback styling.
  bool get isQuiet =>
      this == listening || this == thinking || this == shrug || this == oops;
}

/// Mascot widget for Judge Pip — the "tiny judge" character that hosts the
/// app's verdict, home, loading, error, and share-card surfaces.
///
/// Art is generated by the reference-conditioning pipeline in `tools/pip-gen/`
/// (canon: `assets/pip/PIP_CANON.md`). If an asset fails to load, a circular
/// navy/cream badge with a scales-of-justice glyph renders as a stand-in.
class JudgePip extends StatelessWidget {
  const JudgePip({
    this.size = 56,
    this.pose = PipPose.triumph,
    super.key,
  });

  final double size;
  final PipPose pose;

  /// Set to `false` to force the stub badge (e.g. if art is ever unavailable).
  static const bool kArtReady = true;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      label: 'The tiny judge',
      child: kArtReady ? _buildAsset(context) : _buildStub(),
    );
  }

  Widget _buildAsset(BuildContext context) {
    // Cap decode resolution to the rendered size so we don't hold a full
    // 768px bitmap in memory for an 88px render.
    final dpr = MediaQuery.maybeDevicePixelRatioOf(context) ?? 3.0;
    final cache = (size * dpr).round();
    return Image.asset(
      'assets/pip/${pose.asset}.png',
      width: size,
      height: size,
      fit: BoxFit.contain,
      cacheWidth: cache,
      cacheHeight: cache,
      errorBuilder: (context, error, stack) => _buildStub(),
    );
  }

  Widget _buildStub() {
    final quiet = pose.isQuiet;
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: quiet ? SettleThisColors.cream : SettleThisColors.navy,
        shape: BoxShape.circle,
        border: Border.all(
          color: SettleThisColors.gavelGold,
          width: size > 80 ? 3 : 2,
        ),
        boxShadow: quiet
            ? null
            : [
                BoxShadow(
                  color: SettleThisColors.gavelGold.withValues(alpha: 0.18),
                  blurRadius: 18,
                  spreadRadius: 1,
                  offset: const Offset(0, 4),
                ),
              ],
      ),
      alignment: Alignment.center,
      child: Text(
        '⚖',
        style: TextStyle(
          fontSize: size * 0.5,
          color: quiet
              ? SettleThisColors.navyDeep
              : SettleThisColors.gavelGold,
        ),
      ),
    );
  }
}
