import 'package:flutter/material.dart';

import '../../../app/theme.dart';
import '../domain/verdict.dart';

/// Visual share card. Designed to be captured to PNG via RepaintBoundary,
/// so layout is fixed-width (1080dp) and self-contained — no theme inheritance.
class ShareCardWidget extends StatelessWidget {
  const ShareCardWidget({
    required this.shareCard,
    super.key,
  });

  final ShareCardData shareCard;

  static const double cardWidth = 1080;
  static const double cardHeight = 1350;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: cardWidth,
      height: cardHeight,
      child: Material(
        color: SettleThisColors.cream,
        child: Padding(
          padding: const EdgeInsets.all(72),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const _CardHeader(),
              const SizedBox(height: 64),
              Text(
                shareCard.headline,
                style: const TextStyle(
                  fontFamily: 'Nunito',
                  fontSize: 92,
                  height: 1.05,
                  fontWeight: FontWeight.w900,
                  color: SettleThisColors.navyDeep,
                ),
              ),
              const SizedBox(height: 36),
              Text(
                shareCard.verdictOneLiner,
                style: const TextStyle(
                  fontFamily: 'Nunito',
                  fontSize: 44,
                  height: 1.3,
                  fontWeight: FontWeight.w700,
                  color: SettleThisColors.ink,
                ),
              ),
              const Spacer(),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 28, vertical: 24),
                decoration: BoxDecoration(
                  color: SettleThisColors.navy,
                  borderRadius: BorderRadius.circular(28),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'RULING',
                      style: TextStyle(
                        fontFamily: 'Nunito',
                        fontSize: 28,
                        letterSpacing: 2,
                        fontWeight: FontWeight.w800,
                        color: SettleThisColors.gavelGold,
                      ),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      shareCard.shortRuling,
                      style: const TextStyle(
                        fontFamily: 'Nunito',
                        fontSize: 40,
                        height: 1.3,
                        fontWeight: FontWeight.w700,
                        color: SettleThisColors.cream,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 36),
              const _CardFooter(),
            ],
          ),
        ),
      ),
    );
  }
}

class _CardHeader extends StatelessWidget {
  const _CardHeader();

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Container(
          width: 80,
          height: 80,
          decoration: BoxDecoration(
            color: SettleThisColors.gavelGold,
            borderRadius: BorderRadius.circular(24),
          ),
          child: const Icon(
            Icons.gavel,
            size: 44,
            color: SettleThisColors.navyDeep,
          ),
        ),
        const SizedBox(width: 20),
        const Text(
          'Settle This',
          style: TextStyle(
            fontFamily: 'Nunito',
            fontSize: 40,
            fontWeight: FontWeight.w900,
            color: SettleThisColors.navyDeep,
          ),
        ),
      ],
    );
  }
}

class _CardFooter extends StatelessWidget {
  const _CardFooter();

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          'Generated by Settle This',
          style: TextStyle(
            fontFamily: 'Nunito',
            fontSize: 26,
            color: SettleThisColors.inkSoft,
          ),
        ),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          decoration: BoxDecoration(
            color: SettleThisColors.coral.withValues(alpha: 0.15),
            borderRadius: BorderRadius.circular(999),
            border: Border.all(color: SettleThisColors.coral),
          ),
          child: const Text(
            'AI-generated verdict',
            style: TextStyle(
              fontFamily: 'Nunito',
              fontSize: 22,
              fontWeight: FontWeight.w700,
              color: SettleThisColors.coral,
            ),
          ),
        ),
      ],
    );
  }
}
