import 'package:flutter/material.dart';

import '../../../app/theme.dart';

const String _disclaimer =
    'Settle This is for entertainment and general perspective on everyday '
    'low-stakes disagreements. It is not therapy, legal advice, medical '
    'advice, crisis support, or a substitute for professional help.';

const List<({String title, String body})> _sections = [
  (
    title: 'What we collect',
    body:
        'A pseudonymous user id (Firebase Auth uid), the cases you choose to save, '
        'product analytics, and crash reports. We do not collect your contacts, '
        'health, location, or device-level identifiers unless you grant them '
        'explicitly via the OS.',
  ),
  (
    title: 'AI usage',
    body:
        'Verdicts are generated by an AI model called from our backend. We do not '
        'send your raw input directly to any third party from your device. AI '
        'output is treated as entertainment, not professional advice.',
  ),
  (
    title: 'Sharing',
    body:
        'Share cards leave the app only when you tap the share button. Names, '
        'addresses, phone numbers, and similar identifying details are filtered '
        'before share cards are generated.',
  ),
  (
    title: 'Your controls',
    body:
        'Delete a single saved verdict from its detail page. Delete all saved '
        'data or your entire account from Settings → Delete data.',
  ),
];

class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('Privacy')),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            Card(
              color: SettleThisColors.cream,
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'DISCLAIMER',
                      style: theme.textTheme.labelSmall?.copyWith(
                        fontWeight: FontWeight.w800,
                        color: SettleThisColors.inkSoft,
                        letterSpacing: 0.8,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      _disclaimer,
                      style: theme.textTheme.bodyMedium?.copyWith(height: 1.5),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            ..._sections.map(
              (s) => Padding(
                padding: const EdgeInsets.only(bottom: 16),
                child: Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          s.title.toUpperCase(),
                          style: theme.textTheme.labelSmall?.copyWith(
                            fontWeight: FontWeight.w800,
                            color: SettleThisColors.inkSoft,
                            letterSpacing: 0.8,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          s.body,
                          style: theme.textTheme.bodyMedium?.copyWith(
                            height: 1.5,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
            Center(
              child: Text(
                'Full privacy policy and terms are linked from the App Store / '
                'Google Play listing.',
                textAlign: TextAlign.center,
                style: theme.textTheme.bodySmall?.copyWith(
                  color: SettleThisColors.inkSoft,
                ),
              ),
            ),
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }
}
